// TestCOM.idl : TestCOM 的 IDL 源
//

// 此文件将由 MIDL 工具处理以
// 产生类型库(TestCOM.tlb)和封送处理代码。

import "oaidl.idl";
import "ocidl.idl";

[
	object,
	uuid(a817e7a2-43fa-11d0-9e44-00aa00b6770a),
	dual,	
	pointer_default(unique)
]
interface IComponentRegistrar : IDispatch
{
	[id(1)]	HRESULT Attach([in] BSTR bstrPath);
	[id(2)]	HRESULT RegisterAll();
	[id(3)]	HRESULT UnregisterAll();
	[id(4)]	HRESULT GetComponents([out] SAFEARRAY(BSTR)* pbstrCLSIDs, [out] SAFEARRAY(BSTR)* pbstrDescriptions);
	[id(5)]	HRESULT RegisterComponent([in] BSTR bstrCLSID);
	[id(6)] HRESULT UnregisterComponent([in] BSTR bstrCLSID);
};

[
	object,
	uuid(C5548473-25D9-4A19-9938-9C17B04EBBB6),
	dual,
	nonextensible,
	pointer_default(unique)
]
interface IMyClass : IDispatch{
	[id(1)] HRESULT add([in] LONG a, [in] LONG b, [out,retval] LONG* result);
};
[
	uuid(10E94D51-059F-484D-BFDB-B41B5D5CEF36),
	version(1.0),
	custom(a817e7a1-43fa-11d0-9e44-00aa00b6770a,"{F167A5A5-FD3B-4E91-9A0E-27CD615C1C88}")
]
library TestCOMLib
{
	importlib("stdole2.tlb");
	[
		uuid(F167A5A5-FD3B-4E91-9A0E-27CD615C1C88)		
	]
	coclass CompReg
	{
		[default] interface IComponentRegistrar;
	};
	[
		uuid(B316F12A-378A-455A-AC9F-5EBA24340B90)		
	]
	coclass MyClass
	{
		[default] interface IMyClass;
	};
};

